// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWl4ewBndeqm-ShY8bPBMyyar7pFJzxU',
    appId: '1:47780111924:web:6d59c7ed4c2b3826fecc61',
    messagingSenderId: '47780111924',
    projectId: 'travellapp-4f541',
    authDomain: 'travellapp-4f541.firebaseapp.com',
    storageBucket: 'travellapp-4f541.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkj2ITCkwR_jTuEjb8POGNPKtwdWrfZsY',
    appId: '1:47780111924:android:7cb28b356ce8d5b0fecc61',
    messagingSenderId: '47780111924',
    projectId: 'travellapp-4f541',
    storageBucket: 'travellapp-4f541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdW4UAANUoKVsv8GVo7_dd67XFHGtCA8',
    appId: '1:47780111924:ios:9d07c7005a654e66fecc61',
    messagingSenderId: '47780111924',
    projectId: 'travellapp-4f541',
    storageBucket: 'travellapp-4f541.appspot.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdW4UAANUoKVsv8GVo7_dd67XFHGtCA8',
    appId: '1:47780111924:ios:9d07c7005a654e66fecc61',
    messagingSenderId: '47780111924',
    projectId: 'travellapp-4f541',
    storageBucket: 'travellapp-4f541.appspot.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWl4ewBndeqm-ShY8bPBMyyar7pFJzxU',
    appId: '1:47780111924:web:de94c365810cb3b4fecc61',
    messagingSenderId: '47780111924',
    projectId: 'travellapp-4f541',
    authDomain: 'travellapp-4f541.firebaseapp.com',
    storageBucket: 'travellapp-4f541.appspot.com',
  );
}
